INSERT INTO "tasks" (title, description, status) VALUES
('Update resume', 'Add recent projects and skills', 'PENDING'),
('Clean windows', 'Living room and kitchen windows', 'COMPLETED'),
('Backup files', 'Backup important documents to cloud', 'PENDING'),
('Call insurance', 'Confirm policy details', 'COMPLETED'),
('Buy office supplies', 'Pens, notebooks, and printer paper', 'PENDING'),
('Meditation', '20 minutes mindfulness session', 'COMPLETED'),
('Fix bike', 'Replace chain and brakes', 'PENDING'),
('Prepare tax documents', 'Gather receipts and forms', 'COMPLETED'),
('Grocery restock', 'Vegetables, fruits, and dairy', 'PENDING'),
('Car wash', 'Exterior and interior cleaning', 'COMPLETED'),
('Read articles', 'Catch up on industry news', 'PENDING'),
('Organize emails', 'Delete spam and categorize inbox', 'COMPLETED'),
('Cook dinner', 'Try new pasta recipe', 'PENDING'),
('Walk the dog', 'Evening walk in the park', 'COMPLETED'),
('Plan birthday party', 'Send invitations and order cake', 'PENDING'),
('Pay rent', 'Due on the 1st', 'COMPLETED'),
('Visit dentist', 'Routine check-up and cleaning', 'PENDING'),
('Clean fridge', 'Remove expired items and wipe shelves', 'COMPLETED'),
('Schedule meeting', 'Team project discussion', 'PENDING'),
('Yoga session', '1 hour online class', 'COMPLETED'),
('Update software', 'Install latest updates', 'PENDING'),
('Prepare presentation slides', 'For client meeting', 'COMPLETED'),
('Call mom', 'Catch up and check-in', 'PENDING'),
('Organize books', 'Sort by genre and author', 'COMPLETED'),
('Check mailbox', 'Sort letters and packages', 'PENDING'),
('Plan weekend trip', 'Research locations and hotels', 'COMPLETED'),
('Pay credit card', 'Before due date', 'PENDING'),
('Clean backyard', 'Mow lawn and trim bushes', 'COMPLETED'),
('Finish coding task', 'Complete feature for app', 'PENDING'),
('Water garden', 'Outdoor plants and flowers', 'COMPLETED');
