const defaultSqlBasicSuggestions = <String>[
  'SELECT * FROM ',
  'INSERT INTO ',
  'UPDATE ',
  'DELETE FROM ',
  'CREATE TABLE ',
  'DROP TABLE ',
  'ALTER TABLE ',
  'WHERE ',
  'GROUP BY ',
  'ORDER BY ',
  'JOIN ',
  'LEFT JOIN ',
  'RIGHT JOIN ',
  'INNER JOIN ',
  'UNION ',
  'LIMIT ',
  'OFFSET ',
];
